
import { GoogleGenAI } from "@google/genai";

// Assume process.env.API_KEY is set in the environment
if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const PROMPT_GENERATION_TEMPLATE = `
Analyze the following YouTube video title and keywords to create a master-level, detailed image generation prompt. The prompt must be suitable for AI image generators like DALL-E 3 or Midjourney.

**Video Title:** "{title}"
**Keywords/Style:** "{keywords}"

Construct the output prompt using this exact structure, filling in the bracketed sections with your intelligent analysis. Do not include the original title or keywords in your final output prompt. The output must be ONLY the generated prompt itself, starting with "Professional YouTube Thumbnail...".

--- STRUCTURE ---
Professional YouTube Thumbnail, Ultra Detailed, Photorealistic, High Contrast, 4K, sharp focus.

**Scene Description:** [Intelligently create a vivid scene based on the title. Identify the main subject, action, and emotion. E.g., for a motivational title, describe 'A person at the peak of a mountain at sunrise, arms raised in victory, with an expression of extreme achievement and joy.']

**Composition & Framing:** Dynamic rule of thirds composition. Single, dominant focal point. Expressive, authentic emotion on the subject's face. Eyes are sharp and engaging. Clean, uncluttered background that complements the subject.

**Color & Lighting:** Vibrant, saturated colors that pop. Dramatic, cinematic lighting with strong highlights and deep shadows to create depth and focus. The color palette should be [Choose one based on keywords: energetic/warm for motivational, cool/techy for reviews, dark/mysterious for intrigue, etc.].

**Text & Graphics:** The thumbnail must include bold, impactful, and easy-to-read text overlay. The text should be: '[Extract a short, powerful 2-4 word phrase from the title]'. The font is modern and bold. The text color contrasts highly with its background. Consider a subtle glow or stroke around the text for maximum readability. Include a relevant graphic element like an arrow, circle, or icon to guide the viewer's eye.

**Mood & Goal:** The overall mood is [Determine one from keywords: inspiring, curious, shocking, exciting, etc.] and is designed to achieve a high click-through rate (CTR). It must look professional and competitive on the YouTube platform.
--- END STRUCTURE ---
`;


export const generateThumbnailPrompt = async (title: string, keywords: string): Promise<string> => {
    try {
        const prompt = PROMPT_GENERATION_TEMPLATE
            .replace('{title}', title)
            .replace('{keywords}', keywords || 'general');

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-pro',
            contents: prompt,
        });

        return response.text;
    } catch (error) {
        console.error("Error generating thumbnail prompt:", error);
        throw new Error("Failed to communicate with the AI model for prompt generation.");
    }
};

export const generateThumbnailImage = async (prompt: string): Promise<string> => {
    try {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/jpeg',
                aspectRatio: '16:9',
            },
        });
        
        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            return base64ImageBytes;
        } else {
            throw new Error("No image was generated by the API.");
        }

    } catch (error) {
        console.error("Error generating thumbnail image:", error);
        throw new Error("Failed to communicate with the AI model for image generation.");
    }
};
